FROM centos:7
MAINTAINER XUE RUI<xuerui911@126.com>
WORKDIR /root/

#readme文件
#COPY Readme-DockerCentOS7Bigdata.txt /root/readme.txt

#设置时区为东八区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#添加源
COPY repos/* /etc/yum.repos.d/

#安装系统常用软件
RUN yum -y update && yum -y install iproute wget bash-completion vim dnf nano openssh-server openssh-client python3

#安装scala（spark依赖）
RUN wget https://downloads.lightbend.com/scala/2.13.3/scala-2.13.3.rpm && yum	-y install scala-2.13.3.rpm && rm -f scala-2.13.3.rpm


RUN mkdir -p /opt/module

ADD components/apache-maven-3.6.3-bin.tar.gz /opt/module
ADD components/hadoop-3.3.0.tar.gz /opt/module
ADD components/apache-zookeeper-3.6.2-bin.tar.gz /opt/module
ADD components/apache-hive-3.1.2-bin.tar.gz /opt/module
ADD components/apache-flume-1.9.0-bin.tar.gz /opt/module
ADD components/kafka_2.13-2.6.0.tgz /opt/module
ADD components/v2.0.1.tar.gz /opt/module
ADD components/hbase-2.3.1-bin.tar.gz /opt/module
ADD components/apache-phoenix-5.0.0-HBase-2.0-bin.tar.gz /opt/module
ADD components/jdk-11.0.8.tar.gz /opt/module

RUN mv /opt/module/apache-flume-1.9.0-bin /opt/module/flume-1.9.0
RUN mv /opt/module/apache-hive-3.1.2-bin /opt/module/hive-3.1.2
RUN mv /opt/module/apache-maven-3.6.3 /opt/module/maven-3.6.3
RUN mv /opt/module/apache-phoenix-5.0.0-HBase-2.0-bin /opt/module/phoenix-5.0.0
RUN mv /opt/module/apache-zookeeper-3.6.2-bin /opt/module/zookeeper-3.6.2
RUN mv /opt/module/kafka-eagle-bin-2.0.1 /opt/module/kafka-eagle-2.0.1

#大数据组件环境变量
ENV JAVA_HOME=/opt/module/jdk-11.0.8
ENV MAVEN_HOME=/opt/module/maven-3.6.3
ENV HADOOP_HOME=/opt/module/hadoop-3.3.0
ENV ZK_HOME=/opt/module/zookeeper-3.6.2
ENV HIVE_HOME=/opt/module/hive-3.1.2
ENV FLUME_HOME=/opt/module/flume-1.9.0
ENV KAFKA_HOME=/opt/module/kafka_2.13-2.6.0
ENV HBASE_HOME=/opt/module/hbase-2.3.1
ENV PHN_HOME=/opt/module/phoenix-5.0.0
RUN chmod -R 755 ${MAVEN_HOME}/*

#添加自定义脚本
RUN mkdir -p /opt/module/scripts
ENV SH_HOME=/opt/module/scripts
COPY scripts/* ${SH_HOME}/
RUN chmod -R 755 ${SH_HOME}/*

ENV PATH=$PATH:${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${ZK_HOME}/bin:${HIVE_HOME}/bin:${FLUME_HOME}/bin:${KAFKA_HOME}/bin:${HBASE_HOME}/bin:${PHN_HOME}/bin:$SH_HOME

#以防环境变量失效
RUN touch /etc/profile.d/bigdataenv.sh
RUN echo -e "export JAVA_HOME=/opt/module/jdk-11.0.8\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export MAVEN_HOME=/opt/module/maven-3.6.3\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export HADOOP_HOME=/opt/module/hadoop-3.3.0\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export ENV ZK_HOME=/opt/module/zookeeper-3.6.2\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export ENV HIVE_HOME=/opt/module/hive-3.1.2\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export ENV FLUME_HOME=/opt/module/flume-1.9.0\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export KAFKA_HOME=/opt/module/kafka_2.13-2.6.0\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export HBASE_HOME=/opt/module/hbase-2.3.1\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export PHN_HOME=/opt/module/phoenix-5.0.0\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export SH_HOME=/opt/module/scripts\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export PATH=$PATH:${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${ZK_HOME}/bin:${HIVE_HOME}/bin:${FLUME_HOME}/bin:${KAFKA_HOME}/bin:${HBASE_HOME}/bin:${PHN_HOME}/bin:$SH_HOME\n" >> /etc/profile.d/bigdataenv.sh
RUN echo -e "export JAVA_HOME=/opt/module/jdk-11.0.8\n" >> /root/.bshrc
RUN echo -e "export MAVEN_HOME=/opt/module/maven-3.6.3\n" >> /root/.bshrc
RUN echo -e "export HADOOP_HOME=/opt/module/hadoop-3.3.0\n" >> /root/.bshrc
RUN echo -e "export ENV ZK_HOME=/opt/module/zookeeper-3.6.2\n" >> /root/.bshrc
RUN echo -e "export ENV HIVE_HOME=/opt/module/hive-3.1.2\n" >> /root/.bshrc
RUN echo -e "export ENV FLUME_HOME=/opt/module/flume-1.9.0\n" >> /root/.bshrc
RUN echo -e "export KAFKA_HOME=/opt/module/kafka_2.13-2.6.0\n" >> /root/.bshrc
RUN echo -e "export HBASE_HOME=/opt/module/hbase-2.3.1\n" >> /root/.bshrc
RUN echo -e "export PHN_HOME=/opt/module/phoenix-5.0.0\n" >> /root/.bshrc
RUN echo -e "export SH_HOME=/opt/module/scripts\n" >> /root/.bshrc
RUN echo -e "export PATH=$PATH:${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${ZK_HOME}/bin:${HIVE_HOME}/bin:${FLUME_HOME}/bin:${KAFKA_HOME}/bin:${HBASE_HOME}/bin:${PHN_HOME}/bin:$SH_HOME\n" >> /root/.bshrc
RUN source /etc/profile && source /root/.bashrc

#修改hosts添加集群机器
CMD echo -e "192.168.88.101 hadoop101\n192.168.88.102 hadoop102\n192.168.88.103 hadoop103\n192.168.88.104 hadoop104\n192.168.88.105 hadoop105" >> /etc/hosts

#修改sshd配置:服务端不自动断开,允许root登录，允许空密码登录
CMD sed -i 's/#LoginGraceTime 2m/LoginGraceTime 0/' /etc/ssh/sshd_config
CMD sed -i 's/#PermitRootLogin no/PermitRootLogin yes/' /etc/ssh/sshd_config
CMD sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config


#构建成功时打印
ONBUILD echo "构建成功！"
